# Generated by Django 5.0.1 on 2024-01-13 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RideType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comments', models.TextField()),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('distance', models.CharField(max_length=255)),
                ('speed', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('cafe_stop', models.CharField(max_length=255)),
                ('meeting_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride_manager.meetingpoint')),
                ('rider', models.ManyToManyField(to='ride_manager.rider')),
                ('ride_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride_manager.ridetype')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
