# Generated by Django 5.0.1 on 2024-01-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_manager', '0002_remove_ride_rider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingpoint',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='rider',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ridetype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='ride',
            name='route',
            field=models.URLField(),
        ),
    ]
